version: '3'
services:
  mysql:
    build: db
    container_name: dbcontainer
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
